SportsStore/Controllers/BackgroundController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportsStore.Controllers
{
    public class FilterController : Controller
    {
        public IActionResult Index()
        {
            return View("~/Views/Static/Filter.cshtml");

        }
    }
}

SportsStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;
using System.Linq;

namespace SportsStore.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private Cart cart;

        public CartController(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int productId, int quantity, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.AddItem(product, quantity);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpPost]
        public IActionResult UpdateCart(int productId, int quantity, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.UpdateItem(product, quantity);
            }

            return RedirectToAction("Index", new { returnUrl });
        }


        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportsStore/Controllers/FAQController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportsStore.Controllers
{
    public class FAQController : Controller
    {
        public IActionResult Index()
        {
            return View("~/Views/Static/FAQ.cshtml");
        }
    }
}

SportsStore/Controllers/FilterController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportsStore.Controllers
{
    public class PolicyController : Controller
    {
        public IActionResult Index()
        {
            return View("~/Views/Static/Policy.cshtml");

        }
    }
}

SportsStore/Views/Shared/Background.cshtml
@{
    ViewData["Title"] = "Background";
}

<!-- Page Heading is Here -->
<h1>@ViewData["Background"]</h1>
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>

<body>
    <h3 style="color:#000000">About us</h3>
    <p>
        MRJ Commerce operates entirely as an online clothing retailer, serving customers
        through e-commerce, under the domain mrjcommerce.com. Online clothing retail is a successful industry, finding significant ground in the market for clothing business compared to physical
        brick-and-mortar stores. MRJ Commerce will be important to our customer industry because with customers being able to sell their products online, it helps them out financially, it saves the customers the trouble of driving all the way to a store and walking around to find what they want when they can just do it in the comfort of their own home.
    </p>
    <h3 style="color:#000000">Products and services </h3>
    <p>
        With MRJ commerce operating entirely as an online clothing retailer, we are dedicated to providing flexible shipping options to customers, which will happen in various ways.
        First, we will offer shipping with multiple carriers such as USPS, UPS, and FedEx. We will also allow customers to choose from multiple shipping tiers, including standard, expedited, and express shipping, to further accommodate their needs.
        Should the customer want to sell their own product, they will be eligible to sell a certain number of products per month, and once they’ve reached that amount, they’ll have to start paying a certain amount of fees over that limit, should it be in the same month.
        <li>. Wide variety of clothing (Styles, sizes, colors, brands) </li>
        <li>. Customization options (Colors, fabrics, graphics, size) </li>
        <li>. Flexible shipping options (Multiple carriers, shipping tiers, same-day delivery) </li>
        <li>. Loyalty program with perks (Free shipping, and other benefits) </li>
        <li>. Return product process </li>
    </p>
    <h3 style="color:#000000">Value proposition  </h3>
    <p>
        MRJ commerce will attend to customers' needs such as proposing a certain type of clothing for certain types of weather to the customers, at a great price as well.
        MRJ commerce will also give customers great suggestions on gifts for certain occasions such as Christmas, Birthdays, Mother’s and Father's Day, and Valentine's Day along with a great number of deals of course.
    </p>
    <li>. Suits customer needs for all occasions </li>
    <li>. Customized suggestions based on time of year and trends (Holiday-specific gifts, with corresponding deals) </li>
    <li>. Fast shopping and check-out </li>
    <br />

    @*<img src="~/images/MRJ Commerce.png" asp-append-version="true" alt="MRJ Commerce" height="100">*@


</body>

SportsStore/Views/Shared/FAQ.cshtml
@{
    ViewData["Title"] = "FAQ";
}

<!-- Page Heading is Here -->
<h1>@ViewData["Title"]</h1>

<!-- Add your 10 questions and answers here -->
<dl>

    <dt>Question 1: What products do you sell on the this website? </dt>
    <dd>
        MRJ commerce sells all kinds of clothing products (shirts, shoes, shorts etc), suitable for various occasions and weather conditions.
    </dd>

    <dt>Question 2: Does MRJ commerce have a return policy?</dt>
    <dd>
        MRJ Commerce offers a hassle-free return policy for most items within 30 days of purchase, 
        as long as the items are in their original condition. 
        Please see our Return Policy page for more information and instructions on how to initiate a return.
    </dd>

    <dt>Question 3: What shipping options does MRJ Commerce offer?</dt>
    <dd>
        We provide flexible shipping options, partnering with multiple carriers such as USPS, UPS, and FedEx. Customers can choose from various shipping tiers, including standard, expedited, and express shipping, depending on their needs.
    </dd>

    <dt>Question 4: How can I sell my own clothing items on MRJ Commerce?</dt>
    <dd>MRJ Commerce allows users to sell their clothing items on our platform through our brokerage model, which includes auction and transaction brokers. You can list your items for sale or auction, and MRJ Commerce will handle the platform and advertisement for your products.
    </dd>

    <dt>Question 5: How do I track my order?</dt>
    <dd>
       Once your order has been shipped, you will receive a confirmation email with a tracking number. You can use this number to track your package through the carrier's website or the MRJ Commerce order tracking page.
    </dd>

    <dt>Question 6: Can I buy clothing items as gifts for special occasions?</dt>
    <dd>
        Absolutely! MRJ Commerce offers great suggestions for gifts suitable for various occasions, such as Christmas, Birthdays, Mother's and Father's Day, and Valentine's Day. Look out for special deals and promotions during these periods.
    </dd>

    <dt>Question 7: Is there a limit to the number of products I can sell per month on MRJ Commerce?</dt>
    <dd>
        Yes, there is a limit to the number of products you can sell per month. Once you reach that limit, you will need to pay additional fees for any additional items listed within the same month. Please refer to our Seller Fees page for more information on these limits and fees.
    </dd>

    <dt>Question 8: How do I contact customer support if I have any issues or questions?</dt>
    <dd>
        Our customer support team is available to assist you with any questions or concerns. You can reach us by phone at 904-906-907 or via email at support@mrjcommerce.com. You can also chat with us using our live chat feature.
    </dd>

    <dt>Question 9: Are there any fees for buying products on MRJ Commerce?</dt>
    <dd>
        There are no additional fees for buying products on MRJ Commerce, aside from the product price and applicable shipping costs. However, please note that any taxes or customs fees, if applicable, are the responsibility of the buyer.
    </dd>

    <dt>Question 10: Is MRJ Commerce available on mobile devices?</dt>
    <dd>
        Yes, MRJ Commerce is available on both desktop and mobile devices, offering a seamless shopping experience for customers on the go. Access our website through your mobile browser or download our mobile app for even more convenience.
    </dd>
</dl>

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product
<div class="card m-3 rounded">
    <div class="card-block m-2">
        <div class="card-body">
            <h3 class="card-title">
                <strong>@Model.Name</strong>
            </h3>
            <p class="card-text lead">
                @Model.Description
            </p>
            <span class="float-left bg-success text-white rounded m-2 p-1">
                @Model.Price.ToString("c")
            </span>
            <form id="@Model.ProductID" asp-action="AddToCart"
                  asp-controller="Cart" method="post" class="float-start m-2 p-1">
                <input type="hidden" asp-for="ProductID" />
                <input type="hidden" name="returnUrl"
                       value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                <div class="form-group">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" class="form-control" value="1" min="1" style="width: 80px;" />
                </div>
                <button type="submit" class="btn btn-info btn-sm float-start">
                    Add To Cart
            </form>
        </div>
    </div>
</div>

SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script asp-src-include="lib/jquery/**/jquery.min.js"></script>
    <script asp-src-include="lib/jquery-validation/**/jquery.validate.min.js"></script>
    <script asp-src-include="lib/jquery-validation-unobtrusive/**/*.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header"><h4>@ViewBag.Title</h4></div>
            <a class="btn btn-sm btn-primary float-right" asp-action="Logout" aspcontroller="Account">Log Out</a>
            <div class="card-body">
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-success">@TempData["message"]</div>
                }
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" asp-href-include="lib/font-awesome/css/*.css" />
    <title>MRJ Commerce</title>
    <style>


        html {

    margin: auto;
  position: relative;
  min-height: 100%;
}
body {


  margin-bottom: 75px;
  

}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;

  height: 45px;
  line-height: 45px; 
  background-color: #343a40;
}

        .spacing{
        padding-left:10px;
        padding-right:10px;
        }



            .footer a {
                color: #ffffff;
                text-decoration: none;
            }

                .footer a:hover {
                    color: #cccccc;
                }

        .auth-buttons {
            text-align: right;
            margin-top: 10px;
        }

        ul:not(.dropdown-menu) {
    display: flex;
    flex-wrap: wrap;
    zoom: 1;
 }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse justify-content-between" height="80" style="background-color: #646799;">

        <a class="navbar-brand text-white" href="@Url.Action("Index", "Homepage")">
            <img src="~/images/MRJ Commerce.png" asp-append-version="true"  alt="MRJ Commerce" height="80">
        </a>
    
        
        <form class="form-inline my-2 my-lg-0 d-flex" asp-controller="Product" asp-action="Search" method="get">
            <input class="form-control mr-sm-2" type="search" name="searchTerm" placeholder="Search MRJ Commerce" aria-label="Search" style="width: 300px;">
            
            <button class="btn btn-outline-light my-2 my-sm-0"  type="submit" style="padding: 0; width: 35px;">
                <i class="fa fa-search"></i>
            </button>
        </form>

        <a class="btn btn-dark" href="@Url.Action("Index", "Filter")"><span class="spacing">Filter</span></a>
       
        
        <a class="btn btn-dark" href="@Url.Action("", "")">Products</a>
        
        <a class="btn btn-dark" href="@Url.Action("Index", "Auction")">Auction</a> <!-- Added Access Auction button  4/26/23-->
        <a class="btn btn-dark" asp-controller="Account" asp-action="Create" role="button">Register</a>
       <a class="btn btn-dark" asp-controller="Account" asp-action="Login" role="button">Login</a>
   

            <div class="float-right">
                <div class="container">
            
            @await Component.InvokeAsync("CartSummary")
        </div>
        </div>
    </nav>

    
       

            @RenderBody()  


    <div class="footer">
        <div class="container">
            <div class="text-center">
                <a href="@Url.Action("Index", "Homepage")"><span class="spacing">Homepage</span></a>

                <a href="@Url.Action("Index", "FAQ")"><span class="spacing">FAQ</span></a>

                <a href="@Url.Action("Index", "Background")"><span class="spacing">Background</span></a>

                <a href="@Url.Action("Index", "Policy")"><span class="spacing">Policies</span></a>

                <!-- Added a link to the NewsRelease page -->
                <a href="@Url.Action("Index", "NewsRelease")"><span class="spacing">News Releases</span></a>
            </div>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>